# basic options
title: The Blog
author: Me
email: your-email@domain.com
description: A wonderful blog
twitter_username: tweetcity
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
